# Generated by Django 6.0.4 on 2026-04-14 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_add_employee_profile'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDepartmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_history_from', to='organization.department')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_history', to='enrollment.studentprofile')),
                ('to_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_history_to', to='organization.department')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
