# Generated by Django 6.0.4 on 2026-04-14 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_add_student_department_history'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdepartmenthistory',
            name='from_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='organization.department'),
        ),
        migrations.AlterField(
            model_name='studentdepartmenthistory',
            name='to_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='organization.department'),
        ),
    ]
