# Generated by Django 6.0.4 on 2026-04-14 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_add_course_department_relation'),
        ('enrollment', '0004_update_student_department_history_relations'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='academic_rank',
            field=models.CharField(choices=[('assistant_professor', 'Assistant Professor'), ('associate_professor', 'Associate Professor'), ('professor', 'Professor')], db_index=True, default='assistant_professor', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='academic_year',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollment_status',
            field=models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gpa',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['status', 'registered_at'], name='enrollment__status_89b048_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['academic_term', 'status'], name='enrollment__academi_2f749a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['faculty', 'enrollment_status'], name='enrollment__faculty_e5ca48_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['department', 'academic_year'], name='enrollment__departm_c1a378_idx'),
        ),
    ]
