# Generated by Django 6.0.3 on 2026-04-08 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_global_announcements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('import', 'Import'), ('other', 'Other')], default='other', max_length=20)),
                ('entity_type', models.CharField(help_text='Model name or entity type', max_length=100)),
                ('entity_id', models.CharField(blank=True, help_text='Primary key of the affected entity', max_length=100, null=True)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='Previous values before change')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='New values after change')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='academics_a_entity__bca611_idx'), models.Index(fields=['action', 'created_at'], name='academics_a_action_af7337_idx'), models.Index(fields=['user', 'created_at'], name='academics_a_user_id_a85ffa_idx')],
            },
        ),
    ]
