# Generated by Django 6.0.4 on 2026-04-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_group_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_by', to='academics.course'),
        ),
    ]
