# Generated by Django 6.0.4 on 2026-04-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_add_course_prerequisites'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='departments',
            field=models.ManyToManyField(related_name='courses_offered', to='organization.department'),
        ),
    ]
